# Generated by Django 4.0.2 on 2022-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.FloatField()),
                ('number_of_reviews', models.IntegerField()),
            ],
        ),
    ]
