# Generated by Django 4.0.2 on 2022-03-30 09:33

import HotelReviews.s3_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=HotelReviews.s3_settings.PublicMediaStorage(), upload_to='media/'),
        ),
    ]
