# Generated by Django 4.0.2 on 2022-03-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_hotel_number_of_reviews_alter_hotel_rating'),
        ('reviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.hotel'),
        ),
    ]
